Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.provider("virtualbox") do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  
    config.vm.define("jchamakS") do |master|
      master.vm.hostname = "jchamakS"
      master.vm.network("private_network", ip: "192.168.56.110")
      master.vm.provision("shell", privileged: true, path: "./scripts/master.sh")
      master.vm.provider("virtualbox") do |machine|
        machine.name = "jchamakS"
      end
    end
  end
